# Generated by Django 4.2.3 on 2024-09-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_reservation_time_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine-in', 'dine-in'), ('takeaway', 'takeaway'), ('delivery', 'delivery')], max_length=100),
        ),
    ]
