# Generated by Django 4.2.3 on 2024-09-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6, null=True),
        ),
    ]
