# Generated by Django 4.2.3 on 2024-09-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_menuitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingerdientitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
