# Generated by Django 4.2.3 on 2024-09-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_ingerdientitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(related_name='rel_ingredient', to='main.ingredient'),
        ),
    ]
