# Generated by Django 5.0.7 on 2025-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_ingredient_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to="'menu_images/'"),
        ),
    ]
