# Generated by Django 5.0.7 on 2025-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_menuitem_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
