# Generated by Django 5.0.7 on 2025-05-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_menuitem_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngerdientItem',
            new_name='IngredientItem',
        ),
    ]
